language: bash

services:
  - docker

script:
  - docker image build --build-arg UID=$(id -u) --build-arg=$(id -g) -t hexo-alpine:latest .
  - docker run -d --name=my-hexo-blog -p 4000:4000 hexo-alpine:latest 
  - docker exec -it my-hexo-blog hexo new my-first-post
